import { deltaE2000, rgbToColour, type Colour, type Lab, type RGB } from './color'
export type Point={x:number;y:number}
export type Tone={name:'Highlight'|'Light'|'Base'|'Shadow'|'Deep Shadow'; colour:Colour; interpolated?:boolean}

export function screenToImage(point:Point, viewport:{left:number;top:number;scale:number;pan:Point}, image: {width:number;height:number}):Point { return {x:Math.max(0,Math.min(image.width-1,(point.x-viewport.left-viewport.pan.x)/viewport.scale)),y:Math.max(0,Math.min(image.height-1,(point.y-viewport.top-viewport.pan.y)/viewport.scale))} }
export function imageToScreen(point:Point, viewport:{left:number;top:number;scale:number;pan:Point}):Point{return{x:viewport.left+viewport.pan.x+point.x*viewport.scale,y:viewport.top+viewport.pan.y+point.y*viewport.scale}}

export function sampleRegion(data:Uint8ClampedArray,width:number,height:number,center:Point,size:number):Colour { const pixels:{rgb:RGB;l:number}[]=[];const r=Math.floor(size/2); for(let y=Math.max(0,Math.round(center.y)-r);y<=Math.min(height-1,Math.round(center.y)+r);y++)for(let x=Math.max(0,Math.round(center.x)-r);x<=Math.min(width-1,Math.round(center.x)+r);x++){const i=(y*width+x)*4;if(data[i+3]>=32){const rgb={r:data[i],g:data[i+1],b:data[i+2]};pixels.push({rgb,l:rgbToColour(rgb).lab.l})}} if(!pixels.length)return rgbToColour({r:0,g:0,b:0}); const ls=pixels.map(p=>p.l).sort((a,b)=>a-b),lo=ls[Math.floor(ls.length*.1)],hi=ls[Math.ceil(ls.length*.9)-1];const use=pixels.filter(p=>p.l>=lo&&p.l<=hi); const mean=(key:keyof RGB)=>Math.round(use.reduce((s,p)=>s+p.rgb[key],0)/use.length);return rgbToColour({r:mean('r'),g:mean('g'),b:mean('b')}) }

/** Groups context colours by closeness to base then picks luminance landmarks. */
export function makeToneFamily(base:Colour, context:Colour[]):Tone[]{const related=context.filter(c=>deltaE2000(base.lab,c.lab)<32); const all=[base,...related]; const min=Math.min(...all.map(c=>c.lab.l)),max=Math.max(...all.map(c=>c.lab.l));const choose=(target:number)=>all.reduce((best,c)=>Math.abs(c.lab.l-target)<Math.abs(best.lab.l-target)?c:best,base); const names:Tone['name'][]=['Highlight','Light','Base','Shadow','Deep Shadow']; const targets=[max,base.lab.l+(max-base.lab.l)*.5,base.lab.l,base.lab.l-(base.lab.l-min)*.5,min]; return names.map((name,i)=>({name,colour:choose(targets[i]),interpolated:all.length<3&&name!=='Base'}))}
export function contextSamples(data:Uint8ClampedArray,width:number,height:number,center:Point):Colour[]{const out:Colour[]=[];for(let y=-80;y<=80;y+=20)for(let x=-80;x<=80;x+=20)out.push(sampleRegion(data,width,height,{x:center.x+x,y:center.y+y},21));return out}
export function direction(target:Lab, actual:Lab){const dl=actual.l-target.l,da=actual.a-target.a,db=actual.b-target.b;return {dl,da,db,words:[dl>2?'too light':dl<-2?'too dark':'close in lightness',da>2?'too red/warm':da<-2?'too green/cool':'close in red-green',db>2?'too yellow/warm':db<-2?'too blue/cool':'close in yellow-blue']}}
