import { deltaE2000, labToColour, mixLabs, rgbToColour, type Colour, type Lab } from './color'
export type Paint={code:string;name:string; colour:Colour}
export const CATALOGUE:readonly Paint[]=[
 ['105','Titanium White','#f4f2e8'],['268','Azo Yellow Light','#f6c620'],['270','Azo Yellow Deep','#e89b14'],['393','Azo Red Medium','#c94132'],['366','Quinacridone Rose','#bd315c'],['504','Ultramarine','#263b91'],['535','Cerulean Blue Phthalo','#087faa'],['619','Permanent Green Deep','#17633d'],['409','Burnt Umber','#69442e'],['701','Ivory Black','#272827']
].map(([code,name,hex])=>{const n=parseInt(hex.slice(1),16);return{code,name,colour:rgbToColour({r:n>>16,g:(n>>8)&255,b:n&255})}})
export interface MixingModel { mix(parts:{paint:Paint; amount:number}[]):Colour }
/** Deliberately replaceable first-pass optical model: weighted CIELAB average, not pigment physics. */
export const labMixingModel:MixingModel={mix(parts){return labToColour(mixLabs(parts.map(p=>({lab:p.paint.colour.lab,amount:p.amount}))))}}
export type Recipe={parts:{paint:Paint; percent:number; parts:number}[]; colour:Colour; deltaE:number; complexity:'Simple'|'Complex'}
function compositions(count:number, units:number, min=1, prefix:number[]=[]):number[][] {if(count===1)return units>=min?[[...prefix,units]]:[];const out:number[][]=[];for(let n=min;n<=units-min*(count-1);n++)out.push(...compositions(count-1,units-n,min,[...prefix,n]));return out}
function groups<T>(items:T[], n:number,start=0,prefix:T[]=[]):T[][] {if(n===0)return[prefix];const out:T[][]=[];for(let i=start;i<=items.length-n;i++)out.push(...groups(items,n-1,i+1,[...prefix,items[i]]));return out}
export function optimizeRecipes(target:Lab, model:MixingModel=labMixingModel):{simple:Recipe;complex:Recipe}{ const search=(units:number,complexity:Recipe['complexity'])=>{let best:Recipe|undefined;for(let size=1;size<=4;size++)for(const paints of groups([...CATALOGUE],size))for(const amounts of compositions(size,units)){const raw=amounts.map(a=>a/units),colour=model.mix(paints.map((paint,i)=>({paint,amount:raw[i]}))),d=deltaE2000(target,colour.lab);if(!best||d<best.deltaE-1e-9)best={colour,deltaE:d,complexity,parts:paints.map((paint,i)=>({paint,percent:Math.round(raw[i]*100),parts:amounts[i]}))}} return best!}; return {simple:search(4,'Simple'),complex:search(10,'Complex')} }
export function suggestAddition(target:Lab,current:Recipe,model:MixingModel=labMixingModel){let best:{paint:Paint;deltaE:number}|undefined;for(const paint of CATALOGUE){const next=model.mix([...current.parts.map(p=>({paint:p.paint,amount:p.percent/105})),{paint,amount:5/105}]);const d=deltaE2000(target,next.lab);if(!best||d<best.deltaE)best={paint,deltaE:d}}return best!}
