import { useEffect, useRef, useState } from 'react'
import type { Colour } from './lib/color'
import { direction } from './lib/image-analysis'
import { optimizeRecipes, suggestAddition, type Recipe } from './lib/mixing'
import { storage, type SavedSample } from './lib/storage'
import type { Tone } from './lib/image-analysis'

type Analysis={colour:Colour;tones:Tone[];recipes:Record<string,{simple:Recipe;complex:Recipe}>}
type Loaded={url:string;blob:Blob;width:number;height:number;canvas:HTMLCanvasElement}
const sizes=[9,21,41,81]
async function normalise(file:Blob):Promise<Loaded>{let source:CanvasImageSource,width:number,height:number;try{const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});source=bitmap;width=bitmap.width;height=bitmap.height}catch{const url=URL.createObjectURL(file);const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url});URL.revokeObjectURL(url);source=image;width=image.naturalWidth;height=image.naturalHeight}const max=2560,ratio=Math.min(1,max/Math.max(width,height));width=Math.round(width*ratio);height=Math.round(height*ratio);const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d')!.drawImage(source,0,0,width,height);if('close' in source)(source as ImageBitmap).close();const blob=await new Promise<Blob>(resolve=>canvas.toBlob(b=>resolve(b!), 'image/png'));return{url:URL.createObjectURL(blob),blob,width,height,canvas}}
function Swatch({tone,selected,onClick}:{tone:Tone;selected:boolean;onClick:()=>void}){return <button className={`swatch ${selected?'selected':''}`} onClick={onClick}><i style={{background:tone.colour.hex}}/><span>{tone.name}</span><small>{tone.interpolated?'estimated ':''}{tone.colour.hex}</small></button>}
function RecipeCard({recipe}:{recipe:Recipe}){return <article className="recipe"><b>{recipe.complexity} · ΔE {recipe.deltaE.toFixed(1)}</b><p>{recipe.parts.map(p=><span key={p.paint.code}>{p.paint.code} {p.paint.name}: <strong>{p.percent}%</strong> ({p.parts} parts)</span>)}</p></article>}
export default function App(){const [image,setImage]=useState<Loaded>();const [analysis,setAnalysis]=useState<Analysis>();const [selectedTone,setSelectedTone]=useState('Base');const [region,setRegion]=useState(21);const [zoom,setZoom]=useState(1);const [pan,setPan]=useState({x:0,y:0});const [point,setPoint]=useState({x:0,y:0});const [samples,setSamples]=useState<SavedSample[]>([]);const [notice,setNotice]=useState('Choose a reference photo to start.');const canvasRef=useRef<HTMLCanvasElement>(null);const drag=useRef<{x:number;y:number;px:number;py:number;moved:boolean}|undefined>(undefined);const worker=useRef<Worker|undefined>(undefined);
 useEffect(()=>{storage.getSamples().then(setSamples);storage.getLastImage().then(async saved=>{if(saved){const loaded=await normalise(saved.blob);setImage(loaded);setPoint({x:loaded.width/2,y:loaded.height/2});setNotice('Restored your last on-device image.');setTimeout(()=>analyse({x:loaded.width/2,y:loaded.height/2},loaded),0)}}).catch(()=>{});worker.current=new Worker(new URL('./workers/analyser.worker.ts',import.meta.url),{type:'module'});worker.current.onmessage=e=>{setAnalysis(e.data);setSelectedTone('Base');setNotice('Colour family and recipes ready.');};return()=>worker.current?.terminate()},[])
 useEffect(()=>{if(!image||!canvasRef.current)return;const c=canvasRef.current,ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.scale(zoom,zoom);ctx.translate(pan.x,pan.y);ctx.drawImage(image.canvas,0,0);ctx.restore();const x=(point.x+pan.x)*zoom,y=(point.y+pan.y)*zoom;ctx.strokeStyle='white';ctx.lineWidth=3/zoom;ctx.beginPath();ctx.arc(x,y,12/zoom,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#173a31';ctx.lineWidth=1/zoom;ctx.beginPath();ctx.moveTo(x-18/zoom,y);ctx.lineTo(x+18/zoom,y);ctx.moveTo(x,y-18/zoom);ctx.lineTo(x,y+18/zoom);ctx.stroke()},[image,zoom,pan,point])
 const analyse=(p:{x:number;y:number},source=image)=>{if(!source)return;const data=source.canvas.getContext('2d')!.getImageData(0,0,source.width,source.height).data;setNotice('Analysing on this device…');worker.current?.postMessage({id:Date.now(),data,width:source.width,height:source.height,point:p,size:region})}
 const chooseFile=async(file?:File)=>{if(!file)return;if(!['image/jpeg','image/png','image/webp','image/heic','image/heif'].includes(file.type)&&!file.name.match(/\.hei[cf]$/i)){setNotice('Please select JPEG, PNG, WebP, or a decodable HEIC image.');return}try{const loaded=await normalise(file);setImage(old=>{if(old)URL.revokeObjectURL(old.url);return loaded});setZoom(1);setPan({x:0,y:0});const p={x:loaded.width/2,y:loaded.height/2};setPoint(p);await storage.saveLastImage({id:'last',blob:loaded.blob,width:loaded.width,height:loaded.height,updatedAt:Date.now()});setNotice('Image kept on this device. Tap the photo to sample.');setTimeout(()=>analyse(p,loaded),0)}catch{setNotice('This image could not be decoded by this browser. Try JPEG, PNG, or WebP.')}}
 const pointer=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!image)return;const rect=e.currentTarget.getBoundingClientRect(),baseX=(e.clientX-rect.left)*image.width/rect.width,baseY=(e.clientY-rect.top)*image.height/rect.height;if(e.type==='pointerdown'){e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y,moved:false};return}if(e.type==='pointermove'&&drag.current){const d=drag.current;const dx=(e.clientX-d.x)*image.width/rect.width/zoom,dy=(e.clientY-d.y)*image.height/rect.height/zoom;if(Math.hypot(dx,dy)>5)d.moved=true;if(d.moved)setPan({x:d.px+dx,y:d.py+dy});return}if(e.type==='pointerup'&&drag.current){const moved=drag.current.moved;drag.current=undefined;if(!moved){const p={x:Math.max(0,Math.min(image.width-1,baseX/zoom-pan.x)),y:Math.max(0,Math.min(image.height-1,baseY/zoom-pan.y))};setPoint(p);analyse(p)}}}
 const active=analysis?.tones.find(t=>t.name===selectedTone)??analysis?.tones[2];const save=async()=>{if(!analysis||!image)return;const sample:SavedSample={id:crypto.randomUUID(),imageId:'last',name:`Sample ${samples.length+1}`,point:{x:point.x/image.width,y:point.y/image.height},colour:analysis.colour,tones:analysis.tones,recipes:analysis.recipes,createdAt:Date.now()};await storage.saveSample(sample);setSamples(s=>[...s,sample]);setNotice('Sample saved on this device.')}
 const compare=async(file?:File)=>{if(!file||!active)return;try{const check=await normalise(file),actual=check.canvas.getContext('2d')!.getImageData(0,0,check.width,check.height),rgb={r:actual.data[0],g:actual.data[1],b:actual.data[2]}, {rgbToColour}=await import('./lib/color'),mixed=rgbToColour(rgb),d=direction(active.colour.lab,mixed.lab),recipe=analysis?.recipes[selectedTone]?.complex??optimizeRecipes(active.colour.lab).complex,suggestion=suggestAddition(active.colour.lab,recipe);setNotice(`Mix check ΔE ${(await import('./lib/color')).deltaE2000(active.colour.lab,mixed.lab).toFixed(1)}: ${d.words.join(', ')}. Try a small addition of ${suggestion.paint.code} ${suggestion.paint.name}.`);URL.revokeObjectURL(check.url)}catch{setNotice('Could not analyse that comparison photo.')}}
 return <main><header><div><h1>Pinto</h1><p>Van Gogh basic oils mixer</p></div><strong className="private">🔒 Photos never leave this device</strong></header><section className="intro"><h2>Match a colour from a photo</h2><p>Recipe estimates use photographed colour in CIELAB, not a physical pigment calibration.</p><div className="actions"><label className="button">Camera<input aria-label="Take reference photo" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" capture="environment" onChange={e=>chooseFile(e.target.files?.[0])}/></label><label className="button secondary">Choose photo<input aria-label="Choose reference photo" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={e=>chooseFile(e.target.files?.[0])}/></label></div></section>{image&&<><section className="viewer"><canvas aria-label="Reference image. Tap to select colour; drag to pan." ref={canvasRef} width={image.width} height={image.height} onPointerDown={pointer} onPointerMove={pointer} onPointerUp={pointer}/><div className="magnifier" style={{backgroundImage:`url(${image.url})`,backgroundSize:`${zoom*5*100}%`,backgroundPosition:`${point.x/(image.width-1)*100}% ${point.y/(image.height-1)*100}%`}}>+</div></section><div className="controls"><label>Zoom <input aria-label="Zoom" type="range" min="1" max="8" step=".25" value={zoom} onChange={e=>setZoom(+e.target.value)}/>{zoom.toFixed(2)}×</label><label>Sample area <select value={region} onChange={e=>setRegion(+e.target.value)}>{sizes.map(s=><option key={s}>{s}×{s}</option>)}</select></label><button onClick={()=>analyse(point)}>Resample</button></div></>}
 <p className="notice" role="status">{notice}</p>{analysis&&active&&<><section className="colour"><i style={{background:active.colour.hex}}/><div><h2>{active.name}</h2><p>{active.colour.hex} · sRGB {active.colour.rgb.r}, {active.colour.rgb.g}, {active.colour.rgb.b}</p><p>XYZ {Object.values(active.colour.xyz).map(x=>x.toFixed(1)).join(', ')} · Lab {Object.values(active.colour.lab).map(x=>x.toFixed(1)).join(', ')}</p></div><button onClick={save}>Save sample</button></section><section><h2>Colour family</h2><div className="swatches">{analysis.tones.map(t=><Swatch key={t.name} tone={t} selected={selectedTone===t.name} onClick={()=>setSelectedTone(t.name)}/>)}</div></section><section><h2>Mix recipes</h2><RecipeCard recipe={analysis.recipes[selectedTone].simple}/><RecipeCard recipe={analysis.recipes[selectedTone].complex}/></section><section><h2>Check my mix</h2><p>Photograph a small, evenly lit dab and compare it with {active.name}.</p><label className="button secondary">Capture / import mix<input aria-label="Check my mix photo" type="file" accept="image/*" capture="environment" onChange={e=>compare(e.target.files?.[0])}/></label></section></>}{samples.length>0&&<section><h2>Saved samples ({samples.length})</h2>{samples.map(s=><button key={s.id} className="saved" onClick={()=>{setAnalysis({colour:s.colour,tones:s.tones,recipes:s.recipes});setSelectedTone('Base')}}><i style={{background:s.colour.hex}}/>{s.name}</button>)}</section>}<footer>Fixed catalogue: 105, 268, 270, 393, 366, 504, 535, 619, 409, 701.</footer></main>}
